# Generated by Django 4.2.10 on 2024-02-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('Item_name', models.CharField(max_length=200)),
                ('Item_qty', models.PositiveIntegerField()),
                ('Item_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote_ovr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('Quote_no', models.CharField(max_length=50)),
                ('Quote_date', models.DateField()),
                ('Customer_name', models.CharField(max_length=100)),
                ('Customer_email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=20)),
                ('Currency', models.CharField(choices=[('USD', 'US DOLLAR'), ('EUR', 'EURO'), ('GBP', 'GREAT BRITISH POUND')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='quote_det',
            name='Quote_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.quote_ovr'),
        ),
    ]
