# Generated by Django 4.2.10 on 2024-03-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('Item_name', models.CharField(max_length=200, null=True)),
                ('Item_qty', models.PositiveIntegerField(null=True)),
                ('Item_no', models.CharField(max_length=50, null=True)),
                ('Item_per_unit_price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote_ovr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('Quote_no', models.CharField(max_length=50, unique=True)),
                ('Quote_date', models.DateField(null=True)),
                ('Customer_name', models.CharField(max_length=100, null=True)),
                ('Customer_email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Zipcode', models.CharField(max_length=20, null=True)),
                ('Currency', models.CharField(choices=[('EUR', 'EURO'), ('USD', 'US DOLLAR'), ('GBP', 'GREAT BRITISH POUND')], max_length=4)),
                ('Customer_Type', models.CharField(choices=[('RET', 'Retailer'), ('WHO', 'Wholesaler')], max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='quote_det',
            name='Quote_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.quote_ovr', to_field='Quote_no'),
        ),
    ]
