# Generated by Django 4.2.10 on 2024-02-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_quote_det_quote_ovr_delete_record_quote_det_quote_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Currency',
        ),
    ]
