# Generated by Django 4.2.10 on 2024-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_quote_det_quote_ovr_delete_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_ovr',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
