# Generated by Django 4.2.10 on 2024-03-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_quote_det_quote_ovr_delete_record_quote_det_quote_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote_det',
            old_name='Quote_no',
            new_name='Quote_ref',
        ),
    ]
