# Generated by Django 4.2.10 on 2024-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_quote_ovr_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_ovr',
            name='Currency',
            field=models.CharField(choices=[('USD', 'US DOLLAR'), ('EUR', 'EURO'), ('GBP', 'GREAT BRITISH POUND')], default='EUR', max_length=3),
        ),
    ]
