# Generated by Django 4.2.10 on 2024-02-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='created_by',
        ),
    ]
