# Generated by Django 4.2.10 on 2024-04-17 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_quote_det_item_per_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_ovr',
            name='Phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[1-9]\\d*$')]),
        ),
    ]
