# Generated by Django 4.2.10 on 2024-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_quote_ovr_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_ovr',
            name='Phone',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
