# Generated by Django 4.2.10 on 2024-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_quote_ovr_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_ovr',
            name='Currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'US DOLLAR'), ('GBP', 'GREAT BRITISH POUND')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='quote_ovr',
            name='Phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
