# Generated by Django 4.2.10 on 2024-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_quote_ovr_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_ovr',
            name='Quote_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
