# Generated by Django 4.2.10 on 2024-02-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_quote_ovr_quote_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_det',
            name='Item_name',
        ),
        migrations.RemoveField(
            model_name='quote_det',
            name='Item_no',
        ),
        migrations.RemoveField(
            model_name='quote_det',
            name='Item_qty',
        ),
        migrations.RemoveField(
            model_name='quote_det',
            name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='City',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Customer_email',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Customer_name',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Quote_date',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='State',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='Zipcode',
        ),
        migrations.RemoveField(
            model_name='quote_ovr',
            name='record_created_at',
        ),
    ]
