# Generated by Django 4.2.10 on 2024-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_quote_det_item_name_remove_quote_det_item_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_det',
            name='Item_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quote_det',
            name='Item_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote_det',
            name='Item_qty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='Customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='Customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='Quote_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='Zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
