# Generated by Django 4.2.10 on 2024-02-21 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_quote_det_item_name_quote_det_item_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_det',
            name='record_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='Currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'US DOLLAR'), ('GBP', 'GREAT BRITISH POUND')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='quote_ovr',
            name='record_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
