# Generated by Django 4.2.10 on 2024-03-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_quote_ovr_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_det',
            name='Item_per_unit_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quote_det',
            name='product_line_total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
