# Generated by Django 4.2.10 on 2024-03-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_quote_det_item_per_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_det',
            name='product_line_total',
        ),
    ]
