# Generated by Django 4.2.10 on 2024-03-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_quote_det_product_line_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_det',
            name='Quote_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Qt', to='website.quote_ovr'),
        ),
    ]
