# Generated by Django 4.2.10 on 2024-03-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_quote_det_quote_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_ovr',
            name='Currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'US DOLLAR'), ('GBP', 'GREAT BRITISH POUND')], max_length=4),
        ),
    ]
